### ISSUE TITLE
Right Leg Servo doesn't move

### ISSUE THREAD

**Issue by cparrapa** [G4lile0/Bobwi#2]
Hi G4lile0

Thanks  to other comments i make it work and connect easily with HC-06 Bluetooth module, but somehow the Right Leg Servo doesn't move (already double check different servos, the board and connections), also doesn't make sounds (buzzer pin 10). Is a little bit confusing the libraries of Zowi some of them have bugs and switching to Bitbloq generate some kind of redundancy in variables. Your libraries seems better for Bluetooth, are the last ones?

Overall great job! and thanks.

**Comment by G4lile0** [comment]
Solved.. issue related to the different arduino pin configuration of Zowi and Bobwi,
